import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { readFileSync, existsSync } from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

function getDevOutfile() {
	if (existsSync('dev-config.json')) {
		try {
			const cfg = JSON.parse(readFileSync('dev-config.json', 'utf8'));
			if (typeof cfg.vaultPluginDir === 'string') {
				return `${cfg.vaultPluginDir}/main.js`;
			}
		} catch { /* fall through */ }
	}
	// No dev config — write to cwd so at least the build succeeds
	console.warn('[esbuild] dev-config.json not found. Copy dev-config.json.example and set vaultPluginDir to auto-deploy to your vault.');
	return 'main.js';
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	jsx: 'automatic',
	jsxImportSource: 'preact',
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: prod ? 'main.js' : getDevOutfile(),
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
